export const colorCategory: Record<string, string> = {
  black: 'grey',
  gray: 'grey',
  teal: 'green',
  purple: 'purple',
  indigo: 'blue',
  brown: 'orange',
  tan: 'orange',
  pink: 'pink',
  turquoise: 'blue',
  violet: 'purple',
  beige: 'light',
  green: 'green',
  white: 'light',
  cyan: 'blue',
  orange: 'orange',
  red: 'red',
  fuchsia: 'purple',
  magenta: 'pink',
  gold: 'yellow',
  blue: 'blue',
  yellow: 'yellow',
};
