export type Category = 'inspirational' | 'business' | 'academic' | 'keynote';

interface PresentationConstraints {
  [key: string]: number;
}

export type PresentationConstraintsMap = Record<Category, PresentationConstraints>;

export interface ILimits {
  [key: string]: PresentationConstraintsMap;
}

export type BulletSlideLimits = {
  [textAmount in Category]: {
    [variationName: string]: PresentationConstraints;
  };
};

export const imageLimits = {
  minSlideWidth: 800,
  minSlideHeight: 600,
  minContentWidth: 500,
  minContentHeight: 300,
  minAspectRatio: 0.7,
  maxAspectRatio: 1.6,
};

export const limits: ILimits = {
  titleSlide: {
    inspirational: {
      titleMin: 10,
      titleMax: 40,
    },
    business: {
      titleMin: 10,
      titleMax: 40,
    },
    academic: {
      titleMin: 10,
      titleMax: 40,
    },
    keynote: {
      titleMin: 10,
      titleMax: 40,
    },
  },
  imageTextSlide: {
    inspirational: {
      titleMin: 10,
      titleMax: 52,
      textMin: 100,
      textTotalMax: 400,
      textTopMax: 320,
      textBottomMax: 320,
      textWithoutHeadingMax: 265,
    },
    business: {
      titleMin: 10,
      titleMax: 52,
      textMin: 100,
      textTotalMax: 400,
      textTopMax: 320,
      textBottomMax: 320,
      textWithoutHeadingMax: 265,
    },
    academic: {
      titleMin: 10,
      titleMax: 52,
      textMin: 100,
      textTotalMax: 400,
      textTopMax: 320,
      textBottomMax: 320,
      textWithoutHeadingMax: 265,
    },
    keynote: {
      titleMin: 10,
      titleMax: 52,
      textMin: 100,
      textTotalMax: 400,
      textTopMax: 320,
      textBottomMax: 320,
      textWithoutHeadingMax: 265,
    },
  },
  imageCaptionSlide: {
    inspirational: {
      titleMin: 10,
      titleMax: 56,
      textMin: 0,
      textTotalMax: 125,
      subtitleMin: 0,
      subtitleMax: 48,
    },
    business: {
      titleMin: 10,
      titleMax: 56,
      textMin: 0,
      textTotalMax: 125,
      subtitleMin: 0,
      subtitleMax: 48,
    },
    academic: {
      titleMin: 10,
      titleMax: 56,
      textMin: 0,
      textTotalMax: 125,
      subtitleMin: 0,
      subtitleMax: 48,
    },
    keynote: {
      titleMin: 10,
      titleMax: 56,
      textMin: 0,
      textTotalMax: 125,
      subtitleMin: 0,
      subtitleMax: 48,
    },
  },
  textSlide: {
    inspirational: {
      titleMin: 10,
      titleMax: 45,
      textMin: 100,
      textTotalMax: 900,
      subtitleMin: 10,
      subtitleMax: 88,
    },
    business: {
      titleMin: 10,
      titleMax: 45,
      textMin: 100,
      textTotalMax: 900,
      subtitleMin: 10,
      subtitleMax: 88,
    },
    academic: {
      titleMin: 10,
      titleMax: 45,
      textMin: 100,
      textTotalMax: 900,
      subtitleMin: 10,
      subtitleMax: 88,
    },
    keynote: {
      titleMin: 10,
      titleMax: 45,
      textMin: 100,
      textTotalMax: 900,
      subtitleMin: 10,
      subtitleMax: 88,
    },
  },
};

export const bulletSlideLimits: BulletSlideLimits = {
  inspirational: {
    twoCol: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 196,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    list: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 10,
      titleContentMin: 10,
      titleContentMax: 10,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 10,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    cardLike: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'top-with-cards': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'right-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'top-with-shapes': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 42,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 210,
      bulletsMin: 1,
      bulletsMax: 3,
      sentencesMax: 2,
    },
  },
  business: {
    twoCol: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 196,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    list: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 10,
      titleContentMin: 10,
      titleContentMax: 10,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 10,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    cardLike: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'top-with-cards': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'right-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'top-with-shapes': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 42,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 210,
      bulletsMin: 1,
      bulletsMax: 3,
      sentencesMax: 2,
    },
  },
  academic: {
    twoCol: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 196,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    list: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 10,
      titleContentMin: 10,
      titleContentMax: 10,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 10,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    cardLike: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'top-with-cards': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'right-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'top-with-shapes': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 42,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 210,
      bulletsMin: 1,
      bulletsMax: 3,
      sentencesMax: 2,
    },
  },
  keynote: {
    twoCol: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 196,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    list: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 10,
      titleContentMin: 10,
      titleContentMax: 10,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 10,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    cardLike: {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'top-with-cards': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 6,
      sentencesMax: 2,
    },
    'right-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/2-list': {
      titleMin: 10,
      titleMax: 50,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 60,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 185,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-list': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 60,
      titleContentMin: 10,
      titleContentMax: 50,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 250,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 75,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 155,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-cards-cols': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 90,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 160,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'left-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'right-1/3-numbered': {
      titleMin: 10,
      titleMax: 42,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 56,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 170,
      bulletsMin: 1,
      bulletsMax: 4,
      sentencesMax: 2,
    },
    'top-with-shapes': {
      titleMin: 10,
      titleMax: 65,
      subtitleMin: 10,
      subtitleMax: 58,
      titleContentMin: 10,
      titleContentMax: 42,
      subtitleContentMin: 10,
      subtitleContentMax: 10,
      textContentMin: 50,
      textContentMax: 210,
      bulletsMin: 1,
      bulletsMax: 3,
      sentencesMax: 2,
    },
  },
};
