import { SlideTransition } from '@/interfaces/IPresentation';
import { ITransition } from '@/interfaces/IUsePresentation';
import { ThemeCatalog, ThemeSchema } from '@/interfaces/theme.interface';

export const themeCatalog: ThemeCatalog = {
  light: {
    id: 'light',
    templates: ['light', 'rounded'],
    colors: {
      backgroundColor: '#FFFFFF',
      headlineColor: '#F3F3F3',
      textColor: '#4E5155',
      accentColor: '#111111',
      chartColor: '#111111',
    },
  },
  blue: {
    id: 'blue',
    templates: ['light'],
    colors: {
      backgroundColor: '#F9FBFF',
      headlineColor: '#EDF3FF',
      textColor: '#3D74C8',
      accentColor: '#2D76E9',
      addition: '#2A3D5D',
      chartColor: '#2D76E9',
    },
  },
  yellow: {
    id: 'yellow',
    templates: ['light'],
    colors: {
      backgroundColor: '#FFFEFB',
      headlineColor: '#F9F6EF',
      textColor: '#F7C154',
      accentColor: '#E8A011',
      addition: '#423A2C',
      addition2: '#322F25',
      chartColor: '#E8A011',
    },
  },
  green: {
    id: 'green',
    templates: ['light'],
    colors: {
      backgroundColor: '#FBFFFB',
      headlineColor: '#F3F9EF',
      textColor: '#5DB039',
      accentColor: '#6F9A56',
      addition: '#293A22',
      chartColor: '#6F9A56',
    },
  },
  pink: {
    id: 'pink',
    templates: ['light'],
    colors: {
      backgroundColor: '#FFFBFD',
      headlineColor: '#FCF3FD',
      textColor: '#F67FBE',
      accentColor: '#C93B95',
      addition: '#432D38',
      addition2: '#32252D',
      chartColor: '#C93B95',
    },
  },
  purple: {
    id: 'purple',
    templates: ['light'],
    colors: {
      backgroundColor: '#FFFFFF',
      headlineColor: '#F4EEFC',
      textColor: '#9487F8',
      accentColor: '#6600FF',
      addition: '#3B2E43',
      addition2: '#2F2532',
      chartColor: '#6600FF',
    },
  },
  orange: {
    id: 'orange',
    templates: ['light'],
    colors: {
      backgroundColor: '#FFFCFB',
      headlineColor: '#F7EFEC',
      textColor: '#FF7F4D',
      accentColor: '#DD5E2F',
      addition: '#403833',
      addition2: '#332929',
      chartColor: '#E8A011',
    },
  },
  grey: {
    id: 'grey',
    templates: ['dark', 'rounded'],
    colors: {
      backgroundColor: '#1E202B',
      headlineColor: '#3B3E4B',
      textColor: '#9DA0B0',
      accentColor: '#D1D2D7',
      addition: '#FFFFFF',
      chartColor: '#D1D2D7',
    },
  },
  darkgreen: {
    id: 'darkgreen',
    templates: ['dark'],
    colors: {
      backgroundColor: '#272F1C',
      headlineColor: '#323B25',
      textColor: '#49D259',
      accentColor: '#A0B09D',
      addition: '#FFFFFF',
      chartColor: '#A0B09D',
    },
  },
  darkpurple: {
    id: 'darkpurple',
    templates: ['dark'],
    colors: {
      backgroundColor: '#261C2F',
      headlineColor: '#32203D',
      textColor: '#C86FFF',
      accentColor: '#AC9DB0',
      addition: '#FFFFFF',
      chartColor: '#AC9DB0',
    },
  },
  darkblue: {
    id: 'darkblue',
    templates: ['dark'],
    colors: {
      backgroundColor: '#1C222F',
      headlineColor: '#F6F6F6',
      textColor: '#81C1F5',
      accentColor: '#929FBB',
      addition: '#FFFFFF',
      chartColor: '#929FBB',
    },
  },
  darkorange: {
    id: 'darkorange',
    templates: ['dark'],
    colors: {
      backgroundColor: '#2E1D0E',
      headlineColor: '#F6F6F6',
      textColor: '#DD8E1F',
      accentColor: '#B0A69D',
      addition: '#FFFFFF',
      chartColor: '#B0A69D',
    },
  },
  darkyellow: {
    id: 'darkyellow',
    templates: ['dark'],
    colors: {
      backgroundColor: '#2C2A11',
      headlineColor: '#F6F6F6',
      textColor: '#E0E039',
      accentColor: '#B2B08F',
      addition: '#FFFFFF',
      chartColor: '#B2B08F',
    },
  },
  darkpink: {
    id: 'darkpink',
    templates: ['dark'],
    colors: {
      backgroundColor: '#2A191F',
      headlineColor: '#F6F6F6',
      textColor: '#FE8CDA',
      accentColor: '#D7A7C7',
      addition: '#FFFFFF',
      chartColor: '#D7A7C7',
    },
  },
  darkred: {
    id: 'darkred',
    templates: ['dark'],
    colors: {
      backgroundColor: '#301616',
      headlineColor: '#F6F6F6',
      textColor: '#FF6668',
      accentColor: '#A77778',
      addition: '#FFFFFF',
      chartColor: '#A77778',
    },
  },
  third: {
    id: 'third',
    templates: ['third'],
    colors: {
      backgroundColor: '#2C2A11',
      headlineColor: '#F6F6F6',
      textColor: '#E0E039',
      accentColor: '#F6F6F6',
      chartColor: '#D1D13B',
    },
  },
  futureVision: {
    id: 'futureVision',
    templates: ['futureVision'],
    colors: {
      backgroundColor: '#2FBCC6',
      headlineColor: '#FFFFFF',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  boardReport: {
    id: 'boardReport',
    templates: ['boardReport'],
    colors: {
      backgroundColor: '#1C284D',
      headlineColor: '#FFFFFF',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  corporateVision: {
    id: 'corporateVision',
    templates: ['corporateVision'],
    colors: {
      backgroundColor: '#051724',
      headlineColor: '#90E2ED',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  corporateVisionDarkBlue: {
    id: 'corporateVisionDarkBlue',
    templates: ['corporateVision'],
    colors: {
      backgroundColor: '#1C284E',
      headlineColor: '#BEE8FF',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  corporateVisionLightBlueRed: {
    id: 'corporateVisionLightBlueRed',
    templates: ['corporateVision'],
    colors: {
      backgroundColor: '#FFFFFF',
      headlineColor: '#1D1188',
      textColor: '#000000',
      accentColor: '#000BDA',
      addition: '#FFFFFF',
      chartColor: '#000BDA',
    },
  },
  monthlyReport: {
    id: 'monthlyReport',
    templates: ['monthlyReport'],
    colors: {
      backgroundColor: '#FFFFFF',
      headlineColor: '#333F21',
      textColor: '#333F21',
      accentColor: '#A7977F',
      addition: '#FFFFFF',
      chartColor: '#A7977F',
    },
  },
  fastTurn: {
    id: 'fastTurn',
    templates: ['fastTurn'],
    colors: {
      backgroundColor: '#E4E4E4',
      headlineColor: '#000000',
      textColor: '#403833',
      accentColor: '#788284',
      addition: '#FFFFFF',
      chartColor: '#788284',
    },
  },
  funAndGames: {
    id: 'funAndGames',
    templates: ['funAndGames'],
    colors: {
      backgroundColor: '#474498',
      headlineColor: '#F2B9FA',
      textColor: '#FFFFFF',
      accentColor: 'FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  creativeSpark: {
    id: 'creativeSpark',
    templates: ['creativeSpark'],
    colors: {
      backgroundColor: '#1C284D',
      headlineColor: '#C5F286',
      textColor: '#FFFFFF',
      accentColor: '#7292FC',
      addition: '#FFFFFF',
      chartColor: '#7292FC',
    },
  },
  pitchDeck: {
    id: 'pitchDeck',
    templates: ['pitchDeck'],
    colors: {
      backgroundColor: '#6463FF',
      headlineColor: '#9FFFD2',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      addition: '#FFFFFF',
      chartColor: '#FFFFFF',
    },
  },
  personal: {
    id: 'personal',
    templates: [],
    colors: {
      backgroundColor: '#FFFFFF',
      headlineColor: '#F3F3F3',
      textColor: '#4E5155',
      accentColor: '#111111',
    },
  },
};

export const defaultThemes: ThemeSchema[] = Object.values(themeCatalog);

export const transitionOptions: ITransition[] = [
  { value: SlideTransition.NONE, label: 'none' },
  { value: SlideTransition.SLIDE_BELOW, label: 'slideBelow' },
  { value: SlideTransition.SLIDE_RIGHT, label: 'slideRight' },
  { value: SlideTransition.FADE_IN, label: 'fadeIn' },
];

export const themeSwitchMap: Record<string, string> = {
  light: 'grey',
  grey: 'light',
  yellow: 'darkyellow',
  darkyellow: 'yellow',
  green: 'darkgreen',
  darkgreen: 'green',
  pink: 'darkpink',
  darkpink: 'pink',
  purple: 'darkpurple',
  darkpurple: 'purple',
  orange: 'darkorange',
  darkorange: 'orange',
  blue: 'darkblue',
  darkblue: 'blue',
  red: 'darkred',
  darkred: 'red',
  boardReport: 'blue',
  creativeSpark: 'blue',
  funAngGames: 'purple',
  pitchDeck: 'purple',
  corporateVision: 'blue',
  corporateVisionDarkBlue: 'blue',
  corporateVisionLightBlueRed: 'darkblue',
  monthlyReport: 'darkyellow',
  fastTurn: 'grey',
};
