/** @type {import('tailwindcss').Config} */
import plugin from 'tailwindcss/plugin';

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        dark: '#1E202B',
        light: '#FFFFFF',
        blue: '#0767FD',
        accent: '#E73062',
        darkHeadline: '#030712',
        disabled: '#9CA3AF',
        darkText: '#374151',
        darkBg: '#0C1C2B',
        lightText: '#505050',
        tertiaryText: '#6B7280',
        redText: '#FF2A65',
        secondaryBg: '#FEF5F5',
        titleOnImage: 'var(--titleOnImage)',
        titleBg: 'var(--titleBg)',
        titleText: 'var(--titleText)',
        sectionBg: 'var(--sectionBg)',
        pageBg: 'var(--pageBg)',
        headline: 'var(--headline)',
        sectionHeading: 'var(--sectionHeading)',
        bulletPoints: 'var(--bulletPoints)',
        normalSubHeadline: 'var(--normalSubHeadline)',
        smallSubHeadline: 'var(--smallSubheadline)',
        linkText: 'var(--linkText)',
        normalText: 'var(--normalText)',
        smallText: 'var(--smallText)',
        textOnImage: 'var(--textOnImage)',
        shape: 'var(--shape)',
        shapeText: 'var(--shapeText)',
        shapeStroke: 'var(--shapeStroke)',
        tableBorder: 'var(--tableBorder)',
        statsText: 'var(--statsText)',
        statsShape: 'var(--statsShape)',
        white: '#FFFFFF',
        accentHover: '#5634E0',
        accentActive: '#4D2EC7',
        slush: '#F9683A',
        slushPink: '#F94A3A',
        pink: '#FF3D7B',
        mediumGrey: '#DADADA',
        darkGrey: '#454756',
        greyText: '#414141',
        grey: '#BBC1C8',
        lightGrey: '#F8F9FA',
        lightGreyHover: '#EFF0F2',
        lightGreyPress: '#E5E7EB',
        black: '#0F0F0F',
        deepBlack: '#010101',
        chineseBlack: '#111111',
        eerieBlack: '#191919',
        lightGold: '#AB8E66',
        lightBackgroundGold: '#FBF9F7',
        gold: '#8A7252',
        green: '#304835',
        goldBorder: '#BD9E60',
        darkBanner: '#1F2937',
        mediumGreen: '#122717',
        darkGreen: '#0D1A10',
        successGreen: '#2B6437',
        red: '#EB001C',
        redHover: '#F03D4D',
        darkRed: '#411F21',
        buccaneer: '#6D4D4D',
        chartBlue: '#4F46E5',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        'card-stroke': 'rgba(0, 0, 0, 0.08)',
        pending: 'rgba(0, 0, 0, 0.20)',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'var(--primary-500)',
          foreground: 'hsl(var(--primary-foreground))',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
        },
        secondary: {
          DEFAULT: 'var(--secondary-500)',
          foreground: 'hsl(var(--secondary-foreground))',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
        },
        destructive: {
          DEFAULT: 'var(-alert-500)',
          foreground: 'hsl(var(--destructive-foreground))',
          500: 'var(-alert-500)',
          600: 'var(-alert-600)',
          700: 'var(-alert-700)',
        },
        success: {
          DEFAULT: 'var(-success-500)',
          500: 'var(-success-500)',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        neutral: {
          DEFAULT: 'var(--neutral-400)',
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          960: 'var(--neutral-960)',
        },
        surface: {
          grey: 'var(--surface-grey)',
          white: 'var(--surface-white)',
        },
        text: {
          tertiary: 'var(--text-tertiary)',
          secondary: 'var(--text-secondary)',
          primary: 'var(--text-primary)',
          disabled: 'var(--text-disabled)',
        },
        icon: {
          DEFAULT: 'var(--icon-dark)',
          dark: 'var(--icon-dark)',
          light: 'var(--icon-light)',
        },
        cta: {
          text: {
            dark: 'var(--cta-text-dark)',
            light: 'var(--cta-text-light)',
            link: 'var(--cta-text-link)',
          },
          surface: {
            light: 'var(--cta-surface-light)',
            lightHover: 'var(--cta-surface-light-hover)',
            lightFocus: 'var(--cta-surface-light-focus)',
            dark: 'var(--cta-surface-dark)',
            darkHover: 'var(--cta-surface-dark-hover)',
            darkFocus: 'var(--cta-surface-dark-focus)',
          },
        },
      },
      boxShadow: {
        '3xl': '0 20px 40px 0px rgba(66, 12, 21, 0.24)',
        header: '0px 2px 60px rgba(0, 0, 0, 0.06)',
        'section-shadow':
          '0px 15.76px 44.92px rgba(11, 18, 55, 0.08), 0px 10.51px 44.92px rgba(11, 18, 55, 0.08)',
        img: '0px 16px 40px rgba(11, 18, 55, 0.18), 0px 16px 68.4px rgba(11, 18, 55, 0.08)',
        menus: '0px 6px 12px 0px rgba(0, 0, 0, 0.10)',
        'elevate-3': '0 -1px 12px 0 rgba(0,0,0,.03)',
      },
      width: {
        slideMax: 'var(--slideMaxWidth)',
        content: 'var(--presentationXGap)',
        titleDecorationSize: 'var(--titleDecorationSize)',
      },
      height: {
        imageSlideLineHeight: 'var(--imageSlideLineHeight)',
        maxLogoHeight: 'var(--maxLogoSize)',
        maxIconHeight: 'var(--maxIconSize)',
      },
      size: {
        bulletPoint: 'var(--bulletPointSize)',
        bulletPointWithText: 'var(--bulletPointWithTextSize)',
        normalTextFontSize: 'var(--normalTextFontSize)',
        logoSize: 'var(--logoSize)'
      },
      fontSize: {
        title: ['var(--titleFontSize)', { lineHeight: '100%' }],
        heading: ['var(--headingFontSize)', { lineHeight: '120%' }],
        smallHeading: ['var(--smallHeadingFontSize)', { lineHeight: '125%' }],
        sectionHeading: ['var(--sectionHeadingFontSize)', { lineHeight: '150%' }],
        subheadline: ['var(--subheadline)', { lineHeight: '155%' }],
        smallSubHeadlineSize: ['var(--smallsubheadlineSize)', { lineHeight: '155%' }],
        normalTextFontSize: ['var(--normalTextFontSize)', { lineHeight: '155%' }],
        statsTextFontSize: ['var(--statsTextFontSize)', { lineHeight: '120%' }],
        freeSlideFontSize: ['var(--freeSlideFontSize)', { lineHeight: '155%' }],
        bulletPointText: ['var(--bulletPointText)', { lineHeight: 'var(--bulletPointLineHeight)' }],
        bodySmall: ['var(--bodySmall)', { lineHeight: '150%' }],
        bodyLg: ['var(--bodyLg)', { lineHeight: '120%' }],
        bodySm: ['var(--bodySm)', { lineHeight: '120%' }],
      },
      margin: {
        presentation: 'var(--presentationMargin)',
        contentTop: 'var(--contentMarginTop)',
        contentBottom: 'var(--contentMarginBottom)',
        content: 'var(--contentMargin)',
        freeSlideMargin: 'var(--freeSlideMargin)',
        bulletPointAlign: 'var(--bulletPointAlign)',
        marginBetweenSlides: 'var(--marginBetweenSlides)',
        endScreenMarginBottom: 'var(--marginBottomEndScreen)',
        simpleTableX: 'var(--simpleTableX)',
        simpleTableY: 'var(--simpleTableY)',
        smallMargin: 'var(--smallMargin)',
      },
      padding: {
        presentation: 'var(--presentationMargin)',
        contentTop: 'var(--contentMarginTop)',
        contentBottom: 'var(--contentMarginBottom)',
        content: 'var(--contentMargin)',
        endScreenMarginBottom: 'var(--marginBottomEndScreen)',
        contentItemSpace: 'var(--contentItemSpace)',
        contentMargin: 'var(--contentMargin)',
        simpleTableX: 'var(--simpleTableX)',
        simpleTableY: 'var(--simpleTableY)',
        smallMargin: 'var(--smallMargin)',
      },
      gap: {
        presentation: 'var(--presentationXGap)',
        content: 'var(--contentMargin)',
        smallMargin: 'var(--smallMargin)',
      },
      aspectRatio: {
        '3/2': '3 / 2',
        mobile: '9 / 19',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
        'caret-blink': {
          '0%,70%,100%': {
            opacity: '1',
          },
          '20%,50%': {
            opacity: '0',
          },
        },
        slide: {
          '0%': { transform: 'translateX(-200%) rotate(30deg)' },
          '100%': { transform: 'translateX(270%) rotate(30deg)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        slide: 'slide 3s linear infinite',
      },
      backgroundImage: {
        'default-gradient': 'linear-gradient(127.01deg, #FF8743 1.23%, #FF2068 99.82%)',
        'secondary-gradient': 'linear-gradient(127.01deg, #F94A3A 1.23%, #FF3D7B 99.82%)',
        'progress-gradient': 'linear-gradient(to right, #FFDD43, #FF2068)',
        'empty-team': "url('assets/empty-team-bg.png')",
        'empty-dashboard': "url('assets/empty-dashboard-bg.png')",
        'empty-dashboard-mobile': "url('assets/empty-dashboard-bg-mobile.png')",
      },
      backgroundSize: {
        'size-200': '200% 200%',
      },
      backgroundPosition: {
        'pos-0': '0% 0%',
        'pos-100': '100% 100%',
      },
      screens: {
        'huge-desktop': '2000px',
        'big-desktop': '1800px',
        desktop: '1440px',
        'medium-desktop': '1200px',
        'small-desktop': '1024px',
        tablet: '810px',
        mobile: '375px',
      },
      letterSpacing: {
        mini: 'var(--letterSpacingMini)',
      },
      borderWidth: {
        shapeBorderSize: 'var(--shapeBorderSize)',
        shapeBorderSizeSmall: 'var(--shapeBorderSizeSmall)',
      },
      fontFamily: {
        bodyFont: 'var(--body-font-family)',
        titleFont: 'var(--title-font-family)',
      },
      opacity: {
        8: '0.08',
        92: '0.92',
      },
    },
    container: {
      center: true,
    },
  },
  plugins: [
    // eslint-disable-next-line no-undef
    require('tailwindcss-animate'),
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.text-primaryTitle': {
          fontSize: 'var(--primaryTitle)',
          letterSpacing: 'var(--letterSpacingPrimaryTitle)',
        },
        '.text-secondaryTitle': {
          fontSize: 'var(--secondaryTitle)',
          letterSpacing: 'var(--letterSpacingSecondaryTitle)',
        },
        '.text-sectionTitle': {
          fontSize: 'var(--sectionTitle)',
          letterSpacing: 'var(--letterSpacingSectionTitle)',
        },
        '.text-sectionSubtitle': {
          fontSize: 'var(--sectionSubtitle)',
          letterSpacing: 'var(--letterSpacingSectionSubtitle)',
        },
        '.text-bodyLarge': {
          fontSize: 'var(--bodyLarge)',
        },
        '.text-bodyMedium': {
          fontSize: 'var(--bodyMedium)',
        },
      });
    }),
  ],
};
