import { ISlideVariation } from '@/interfaces/ISlideVariation';

export const listVariations: ISlideVariation[] = [
  {
    type: 'cardLike',
    imageClassName: 'hidden',
    plainTextClassName: 'text-normalTextFontSize text-normalText w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading mb-content font-titleFont',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-3 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints rounded-full me-content text-shape text-bulletPointText font-bold flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
    layoutContainerClassName: 'p-presentation',
  },
  {
    type: 'cardLike-without-subtitle',
    imageClassName: 'hidden',
    plainTextClassName: 'text-normalTextFontSize text-normalText w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading mb-content font-titleFont',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-3 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints rounded-full me-content text-shape text-bulletPointText font-bold flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
    layoutContainerClassName: 'p-presentation',
  },
  {
    type: 'twoCol',
    imageClassName: 'hidden',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading mb-content font-titleFont',
    textContainerClassName: 'w-full mt-presentation',
    containerClassName: 'grid grid-cols-2',
    contentSubtitleClassName:
      'text-bulletPoints text-normalTextFontSize font-semibold w-10/12 font-bodyFont',
    bulletPointClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop',
    imageContainerClassName: 'hidden',
    layoutContainerClassName: 'p-presentation',
  },
  {
    type: 'twoCol-without-subtitle',
    imageClassName: 'hidden',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading mb-content font-titleFont',
    textContainerClassName: 'w-full mt-presentation',
    containerClassName: 'grid grid-cols-2',
    contentSubtitleClassName:
      'text-bulletPoints text-normalTextFontSize font-semibold w-10/12 font-bodyFont',
    bulletPointClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop',
    imageContainerClassName: 'hidden',
    layoutContainerClassName: 'p-presentation',
  },
  {
    type: 'list',
    imageClassName: 'hidden',
    plainTextClassName: 'text-normalText text-subheadline w-8/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading mb-content font-titleFont',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
    layoutContainerClassName: 'p-presentation',
  },
  {
    type: 'top-with-cards',
    imageClassName: 'size-full object-cover',
    imageContainerClassName: 'w-full h-1/3',
    plainTextClassName: 'text-normalTextFontSize text-normalText w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'flex',
    containerClassName: 'grid grid-cols-2 gap-content',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'p-presentation h-2/3 w-full',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints rounded-full me-content text-shape text-bulletPointText font-bold flex items-center justify-center',
    showOrderNumber: true,
    layoutContainerClassName: 'flex flex-col-reverse size-full',
  },
  {
    type: 'left-1/2-list',
    imageContainerClassName: 'w-1/2',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'font-bold text-smallHeading text-headline font-titleFont',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-1/2',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full h-full',
  },
  {
    type: 'right-1/2-list',
    imageContainerClassName: 'w-1/2',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'font-bold text-headline text-smallHeading font-titleFont',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-1/2',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full flex-row-reverse h-full',
  },
  {
    type: 'left-1/3-list',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-2/3',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full h-full',
  },
  {
    type: 'right-1/3-list',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-2/3',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full h-full flex-row-reverse',
  },
  {
    type: 'left-1/3-list-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-2/3',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full h-full',
  },
  {
    type: 'right-1/3-list-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-content flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-contentTop p-presentation w-2/3',
    contentSubtitleClassName: 'hidden font-bodyFont',
    bulletPointClassName:
      'size-bulletPoint bg-bulletPoints font-bold rounded-full mt-bulletPointAlign me-content',
    layoutContainerClassName: 'flex w-full h-full flex-row-reverse',
  },
  {
    type: 'right-1/3-cards',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-10/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full flex-row-reverse h-full',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'flex flex-col gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'left-1/3-cards',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-10/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full h-full',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'flex flex-col gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'right-1/3-cards-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full flex-row-reverse h-full',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'flex flex-col gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'left-1/3-cards-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full h-full',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'flex flex-col gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'left-1/3-cards-cols',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full h-full',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-2 gap-content mt-content',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'right-1/3-cards-cols',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-subheadline w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    layoutContainerClassName: 'flex w-full h-full flex-row-reverse',
    textContainerClassName:
      'flex bg-shape border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-2 gap-content mt-content',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'left-1/3-numbered',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-presentation flex',
    containerClassName: 'flex flex-col',
    contentSubtitleClassName: 'hidden',
    layoutContainerClassName: 'flex w-full h-full',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'right-1/3-numbered',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-presentation flex',
    containerClassName: 'flex flex-col',
    contentSubtitleClassName: 'hidden',
    layoutContainerClassName: 'flex w-full h-full flex-row-reverse',
    pageContainerClassName: 'pt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'left-1/3-numbered-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-presentation flex',
    containerClassName: 'flex flex-col',
    contentSubtitleClassName: 'hidden',
    layoutContainerClassName: 'flex w-full h-full',
    pageContainerClassName: 'mt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'right-1/3-numbered-without-subtitle',
    imageContainerClassName: 'w-1/3',
    imageClassName: 'size-full object-cover',
    plainTextClassName: 'text-normalText text-normalTextFontSize w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: 'w-full mt-presentation flex',
    containerClassName: 'flex flex-col',
    contentSubtitleClassName: 'hidden',
    layoutContainerClassName: 'flex w-full h-full flex-row-reverse',
    pageContainerClassName: 'pt-contentTop w-2/3 p-presentation',
    bulletPointClassName:
      'size-bulletPointWithText bg-bulletPoints font-bold rounded-full me-content text-shape text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
  },
  {
    type: 'top-with-shapes',
    imageClassName: 'size-full object-cover',
    imageContainerClassName: 'w-full h-1/3',
    plainTextClassName: 'text-normalTextFontSize text-normalText w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading font-titleFont mb-content',
    textContainerClassName: '',
    containerClassName: 'grid grid-cols-3 gap-content',
    contentSubtitleClassName:
      'text-bulletPoints text-normalTextFontSize font-semibold w-10/12 font-bodyFont hide-numbers mt-content',
    pageContainerClassName: 'p-presentation h-2/3 w-full',
    bulletPointClassName:
      'bg-shape text-normalTextFontSize text-shapeText font-bold flex items-center p-content w-full rounded-r arrow-shape font-bodyFont font-bold',
    showOrderNumber: true,
    layoutContainerClassName: 'flex flex-col-reverse size-full',
  },
];

export const mobileVariations: ISlideVariation[] = [
  {
    type: 'cardLike',
    plainTextClassName: 'text-sm text-normalText  font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize  font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName:
      'flex bg-shape py-3 border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints rounded-full me-content text-shape text-xs font-bold text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'twoCol',
    plainTextClassName: 'text-normalText text-sm w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-base font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont mt-contentTop line-clamp-3',
    textContainerClassName: 'w-full mt-presentation',
    containerClassName: 'grid grid-cols-1 ',
    contentSubtitleClassName: 'text-bulletPoints text-sm font-semibold w-10/12 font-bodyFont',
    bulletPointClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'list',
    plainTextClassName: 'text-normalText text-sm w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName: 'w-full mt-presentation flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-8 sm:mt-10 p-presentation',
    contentSubtitleClassName: 'hidden',
    bulletPointClassName:
      'size-bulletPoint bg-shapeText font-bold rounded-full mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'top-with-cards',
    plainTextClassName: 'text-sm text-normalText font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName: 'flex py-3  p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints rounded-full font-bold me-content text-shape text-xs text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'left-1/3-cards',
    plainTextClassName: 'text-sm text-normalText font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName:
      'flex bg-shape py-3 border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints font-bold rounded-full me-content text-shape text-xs text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'right-1/3-cards',
    plainTextClassName: 'text-sm text-normalText font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName:
      'flex bg-shape py-3 border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints rounded-full font-bold me-content text-shape text-xs text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'left-1/3-cards-cols',
    plainTextClassName: 'text-sm text-normalText font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName:
      'flex bg-shape py-3 border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints rounded-full font-bold me-content text-shape text-xs text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'right-1/3-cards-cols',
    plainTextClassName: 'text-sm text-normalText font-bodyFont',
    subtitleClassName: 'text-normalText text-smallSubHeadlineSize font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName:
      'flex bg-shape py-3 border border-2 border-shapeStroke p-content card-like-list',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'h-6 w-6 bg-bulletPoints rounded-full font-bold me-content text-shape text-xs text-bulletPointText flex items-center justify-center',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
  {
    type: 'left-1/3-numbered',
    plainTextClassName: 'text-normalText text-sm w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-base font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont mt-contentTop line-clamp-3',
    textContainerClassName: 'w-full mt-presentation',
    containerClassName: 'grid grid-cols-1 ',
    contentSubtitleClassName: 'text-bulletPoints text-sm font-semibold w-10/12 font-bodyFont',
    bulletPointClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'right-1/3-numbered',
    plainTextClassName: 'text-normalText text-sm w-10/12 font-bodyFont',
    subtitleClassName: 'text-normalText text-base font-titleFont',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont mt-contentTop line-clamp-3',
    textContainerClassName: 'w-full mt-presentation',
    containerClassName: 'grid grid-cols-1 ',
    contentSubtitleClassName: 'text-bulletPoints text-sm font-semibold w-10/12 font-bodyFont',
    bulletPointClassName: 'hidden',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'right-1/2-list',
    plainTextClassName: 'text-normalText text-sm w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName: 'w-full mt-presentation flex items-top',
    containerClassName: '',
    pageContainerClassName: 'pt-8 sm:pt-10 p-presentation',
    contentSubtitleClassName: 'hidden',
    bulletPointClassName:
      'size-bulletPoint bg-shapeText rounded-full font-bold mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'left-1/2-list',
    plainTextClassName: 'text-normalText text-sm w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName: 'w-full mt-presentation flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-8 sm:mt-10 p-presentation',
    contentSubtitleClassName: 'hidden',
    bulletPointClassName:
      'size-bulletPoint bg-shapeText rounded-full font-bold mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'right-1/3-list',
    plainTextClassName: 'text-normalText text-sm w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-2xl mb-content font-titleFont line-clamp-3',
    textContainerClassName: 'w-full mt-presentation flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-8 sm:mt-10 p-presentation',
    contentSubtitleClassName: 'hidden',
    bulletPointClassName:
      'size-bulletPoint bg-shapeText rounded-full font-bold mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'left-1/3-list',
    plainTextClassName: 'text-normalText text-sm w-11/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:ext-2xl mb-content font-titleFont',
    textContainerClassName: 'w-full mt-presentation flex items-top',
    containerClassName: '',
    pageContainerClassName: 'mt-8 sm:mt-10 p-presentation',
    contentSubtitleClassName: 'hidden',
    bulletPointClassName:
      'size-bulletPoint bg-shapeText rounded-full font-bold mt-bulletPointAlign me-content',
    imageContainerClassName: 'hidden',
  },
  {
    type: 'top-with-shapes',
    plainTextClassName: 'text-sm text-normalText w-10/12 font-bodyFont',
    subtitleClassName: 'hidden',
    slideHeadingClassName:
      'text-[28px] text-headline font-bold sm:text-smallHeading mb-content font-titleFont',
    textContainerClassName: 'p-content',
    containerClassName: 'grid grid-cols-1 gap-content pt-presentation',
    contentSubtitleClassName:
      'text-bulletPoints text-normalTextFontSize font-semibold w-10/12 font-bodyFont hide-numbers mt-content',
    pageContainerClassName: 'mt-8 sm:mt-contentTop p-presentation',
    bulletPointClassName:
      'bg-shape text-normalTextFontSize flex items-center font-bold p-content w-full rounded-r arrow-shape font-bodyFont font-bold',
    showOrderNumber: true,
    imageContainerClassName: 'hidden',
  },
];
