import { ISlideVariation } from '@/interfaces/ISlideVariation';

export const variations: ISlideVariation[] = [
  {
    type: 'right',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex size-full flex-col h-full p-content',
    chartContainerClassName:
      'w-full h-full flex flex-row items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-[75%] h-[85%] max-w-[1200px]',
    slideHeadingClassName: 'text-headline font-bold text-smallHeading mb-content font-titleFont',
    textContainerClassName: '',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-bulletPointText font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText',
    statsValueClassName: 'text-normalTextFontSize font-semibold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'rightWithText',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex flex-row-reverse size-full h-[85%] mt-content',
    chartContainerClassName:
      'w-1/2 flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-[70%] max-w-[1200px]',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    subtitleClassName: 'hidden',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/2 pr-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold',
    statsValueClassName: 'text-normalTextFontSize font-bold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'left',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex size-full flex-col h-full p-content',
    chartContainerClassName:
      'w-full h-full flex flex-row items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-[75%] h-[85%] max-w-[1200px]',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content pl-presentation font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    textContainerClassName: 'h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-bulletPointText font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold',
    statsValueClassName: 'text-normalTextFontSize font-semibold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'leftWithText',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex flex-row size-full h-[85%] mt-content',
    chartContainerClassName:
      'w-1/2 flex flex-col-reverse items-center justify-end p-content bg-shape gap-content',
    chartClassName: 'w-full h-[70%] max-w-[1200px]',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/2 pl-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content font-titleFont pl-presentation',
    subtitleClassName: 'hidden',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold',
    statsValueClassName: 'text-normalTextFontSize font-semibold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'single-chart',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex w-full h-[85%] flex-col',
    chartContainerClassName:
      'w-full h-full flex flex-row items-center justify-center bg-shape gap-content mt-content',
    chartClassName: 'w-[80%] h-[90%] max-w-[1200px] mt-content',
    textContainerClassName: 'self-start mt-presentation px-presentation',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-bulletPointText font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-1 gap-content w-full mt-content',
    statsClassName: 'flex flex-col px-content py-smallMargin bg-statsShape text-statsText',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold',
    statsValueClassName: 'text-normalTextFontSize font-semibold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex flex-col gap-smallMargin'
  },
  {
    type: 'two-charts',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'grid grid-cols-2 w-full h-[80%] gap-content mt-content' ,
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse relative bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px] pr-content',
    textContainerClassName: 'flex flex-col p-content',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    subTextContainerClassName: 'flex flex-row gap-content w-full',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-bulletPointText font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold' ,
    statsValueClassName: 'text-normalTextFontSize font-semibold',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'three-charts',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'grid grid-cols-3 w-full h-[90%] gap-content',
    chartContainerClassName:
      'w-full h-[90%] flex flex-col-reverse relative bg-shape gap-content mt-content',
    chartClassName: 'w-full h-full max-w-[1200px] pr-content',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont',
    textContainerClassName: 'm-content flex flex-col',
    subTextContainerClassName: 'flex flex-row gap-content',
    subTextClassName: 'w-1/2 bg-slate-300 p-content',
    plainTextClassName: 'text-bulletPointText font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin',
    statsTextClassName: 'text-bulletPointText text-statsText font-bold',
    statsValueClassName: 'text-normalTextFontSize font-semibold ',
    statsNameClassName: 'text-bulletPointText',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'four-charts',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'grid grid-cols-2 grid-rows-2 w-full h-[80%] gap-content',
    chartContainerClassName:
      'w-full h-full flex items-center justify-center bg-shape gap-content',
    chartClassName: 'w-[65%] h-full max-w-[1200px] mt-presentation',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont mb-content',
    textContainerClassName: 'h-full w-[35%] p-content',
    subTextContainerClassName: 'flex flex-col items-start gap-content h-full',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-statsTextFontSize font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-bulletPointText text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-1 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin text-bulletPointText',
    statsTextClassName: 'text-statsText text-statsTextFontSize font-bold',
    statsValueClassName: 'font-semibold text-normalTextFontSize',
    statsNameClassName: 'text-statsTextFontSize',
    statsSectionClassName: 'flex gap-smallMargin'
  },
  {
    type: 'six-charts',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'grid grid-cols-3 grid-rows-2 w-full h-[85%] gap-content',
    chartContainerClassName:
      'w-full h-[90%] flex items-center justify-center bg-shape gap-content',
    chartClassName: 'w-[65%] h-full max-w-[1200px] mt-presentation',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content font-titleFont',
    subtitleClassName: 'text-normalText text-subheadline w-8/12 font-titleFont mb-content',
    textContainerClassName: 'h-full w-[35%] p-content pl-smallMargin',
    subTextContainerClassName: 'flex flex-col items-start gap-content h-full',
    subTextClassName: 'w-full bg-slate-300 pl-content pr-content',
    plainTextClassName: 'text-statsTextFontSize font-semibold text-normalText mt-content',
    statsTitleClassName: 'text-bulletPointText text-normalSubHeadline font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-1 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-statsShape text-statsText w-full p-smallMargin text-bulletPointText',
    statsTextClassName: 'text-statsText text-statsTextFontSize font-bold',
    statsValueClassName: 'font-semibold text-bulletPointText',
    statsNameClassName: 'text-statsTextFontSize',
    statsSectionClassName: 'flex flex-col gap-smallMargin'
  },
];

export const mobileVariations: ISlideVariation[] = [
  {
    type: 'right',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
  {
    type: 'left',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
  {
    type: 'single-chart',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },

  {
    type: 'two-charts',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
  {
    type: 'three-charts',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
  {
    type: 'four-charts',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
  {
    type: 'six-charts',
    containerClassName: 'flex size-full flex-col h-full p-content gap-content',
    chartContainerClassName:
      'w-full h-full flex flex-col-reverse items-center justify-center p-content bg-shape gap-content',
    chartClassName: 'w-full h-full max-w-[1200px]',
    textContainerClassName: 'w-full h-full',
    subTextContainerClassName: 'flex flex-col gap-content',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline font-bodyFont mt-content',
    statsTitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
    statsContainerClassName: 'grid grid-cols-2 gap-content w-full mt-content',
    statsClassName: 'flex flex-col bg-pageBg w-full',
    statsTextClassName: 'text-bulletPointText text-shapeText font-bold',
    statsValueClassName: 'text-normalTextFontSize text-shapeText font-semibold',
    statsNameClassName: 'text-bulletPointText text-shapeText',
  },
];
