import { ISlideVariation } from '@/interfaces/ISlideVariation';

export const variations: ISlideVariation[] = [
  {
    type: 'left',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex size-full h-[85%] mt-content',
    imageContainerClassName: 'w-1/2 flex h-full items-start justify-center overflow-hidden',
    imageClassName: 'object-contain size-full screen',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/2 pl-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
  {
    type: 'right',
    pageContainerClassName: 'p-presentation size-full py-contentTop',
    containerClassName: 'flex flex-row-reverse w-full h-[85%] mt-content',
    imageContainerClassName: 'object-contain w-1/2 flex h-full items-start justify-center overflow-hidden',
    imageClassName: 'size-full screen',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/2 pr-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
  {
    type: 'center',
    pageContainerClassName: 'p-presentation size-full py-contentTop',
    containerClassName: 'flex w-full h-[95%] mt-content justify-start justify-center',
    imageContainerClassName: 'w-3/4 h-full flex items-start justify-center overflow-hidden',
    imageClassName: 'object-contain w-full h-full screen',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/2 pr-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
    {
    type: 'right-2/3',
    pageContainerClassName: 'p-presentation size-full py-contentTop',
    containerClassName: 'flex flex-row-reverse w-full h-[85%] mt-content',
    imageContainerClassName: 'w-2/3 flex h-full items-start justify-center overflow-hidden',
    imageClassName: 'object-contain size-full screen',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/3 pr-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
  {
    type: 'left-2/3',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex w-full h-[85%] mt-content',
    imageContainerClassName: 'w-2/3 flex h-full items-start justify-center overflow-hidden',
    imageClassName: 'object-contain size-full screen',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-1/3 pl-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
  {
    type: 'top',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex flex-col w-full h-[95%] mt-content gap-content',
    imageContainerClassName: 'w-full flex h-2/3 items-start justify-center overflow-hidden',
    imageClassName: 'object-contain max-h-full screen m-auto',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-full h-1/3 pl-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
  {
    type: 'bottom',
    pageContainerClassName: 'p-presentation w-full h-full py-contentTop',
    containerClassName: 'flex flex-col-reverse w-full h-[95%] mt-content ',
    imageContainerClassName: 'w-full flex h-2/3 items-start justify-center overflow-hidden',
    imageClassName: 'object-contain max-h-full screen m-auto',
    slideHeadingClassName: 'text-headline font-semibold text-smallHeading mb-content',
    textContainerClassName: 'w-full',
    subTextContainerClassName: 'w-full h-1/3 pl-presentation',
    subTextClassName: 'w-full bg-slate-300 p-content',
    plainTextClassName: 'text-normalTextFontSize text-subheadline text-normalText font-bodyFont ',
    subtitleClassName: 'text-normalTextFontSize text-shapeText font-bodyFont font-semibold',
  },
];
